# VSCode: Shift + Alt + P
openapi: '3.0.3'
info:
  title: WSLManager API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /api/distributions:
    get:
      tags:
        - distributions
      summary: ディストリビューションのリストを取得する
      description: ディストリビューション
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: '#/components/schemas/Distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
components:
  schemas:
    Distribution:
      type: object
      required:
        - isDefault
        - name
        - state
        - version
      properties:
        isDefault:
          type: boolean
          example: true
        name:
          type: string
          example: Ubuntu
        state:
          type: string
          example: Running
        version:
          type: string
          example: 2.0
