# VSCode: Shift + Alt + P
openapi: '3.0.3'
info:
  title: WSLManager API
  version: '1.0'
servers:
  - url: https://api.server.test/api/v1
paths:
  /distributions:
    get:
      tags:
        - distributions
      summary: ディストリビューションのリストを取得する
      description: ディストリビューション
      responses:
        '200':
          description: ディストリビューションリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  items:
                    $ref: './responses/distribution.yaml#/components/schemas/response_distribution'
                  example:
                    isDefault: true
                    name: 'Ubuntu'
                    state: 'Running'
                    version: '2.0'
